[package]
name = "snake"
version = "0.1.0"
authors = ["ZJ <jefferyzhang1013@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston = "0.55.0"
piston_window = "0.131.0"
rand = "0.8.5"